# Generated by Django 3.1.1 on 2020-10-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_wateredevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='wateredevent',
            name='watered_on',
            field=models.DateTimeField(),
        ),
    ]
