# Generated by Django 3.1.1 on 2020-12-12 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0005_wateredevent_watered_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='watering_day',
        ),
        migrations.AddField(
            model_name='plant',
            name='danger_threshold',
            field=models.DurationField(help_text='Plant will be shown in the "Water Now" section of the dashboard after this much time has elapsed since the last watering', null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='warning_threshold',
            field=models.DurationField(help_text='Plant will be shown in the "Water Soon" section of the dashboard after this much time has elapsed since the last watering', null=True),
        ),
    ]
